apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-sample-service
  description: Sample React web app
  labels:
    system: web-apps
  tags:
    - javascript
    - react
  links:
    - url: https://github.com/bcamishrapr/backstage-per-test
      title: Backstage Sample Service GitHub
      icon: code
  annotations:
    pagerduty.com/integration-key: c9181af33a984c06d01144f420df074e
    opsgenie.com/component-selector: 'job:"kube-state-metrics" AND status: open'
    opsgenie.com/team: 'IncidentManager'
    jenkins.io/github-folder: 'bcamishrapr/backstage-per-test'
    fossa.io/project-name: backstage-sample-service
    snyk.io/org-name: prasoon
    snyk.io/project-ids: 1aff69bc-de69-4d0c-b069-187b159c4465
    github.com/project-slug: 'bcamishrapr/backstage-per-test'
    goharbor.io/repository-slug: 'bcamishrapr/backstage-per-test'
    backstage.io/techdocs-ref: dir:.
    roadie-backstage-pull-requests/default-filter: state:all
    grafana/tag-selector: "prometheus"
spec:
  type: service
  lifecycle: experimental
  owner: bcamishrapr
  dependsOn: ['resource:artists-db']
